language: node_js
node_js:
  - "6.9.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - mongodb

notifications:
  irc:
    channels:
      - "irc.freenode.org#periodicjs"
    template:
      - "Build by %{author} :"
      - "Git Info: %{branch} - %{commit} with the message %{commit_message}"
      - "Travis states: %{message}"
      - "Build Details: %{build_url}"
      - "Change View: %{compare_url}"
      - "result = %{result}"
      - "elapsed time... %{duration}"
    use_notice: true
    skip_join: false

install:
  - npm install  grunt-cli istanbul -g
  - npm install 
  # - npm install --skip_app_post_install=true

branches:
  only:
    - master
    - periodic10
    - devel
git:
  submodules: false

script:
  - npm set progress=false && grunt test
